{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-08-22T16:06:15",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://bugs.python.org/issue35907"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://github.com/python/cpython/pull/11842"
                },
                {
                    "name": "107549",
                    "tags": [
                        "vdb-entry",
                        "x_refsource_BID"
                    ],
                    "url": "http://www.securityfocus.com/bid/107549"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://security.netapp.com/advisory/ntap-20190404-0004/"
                },
                {
                    "name": "openSUSE-SU-2019:1273",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html"
                },
                {
                    "name": "openSUSE-SU-2019:1580",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html"
                },
                {
                    "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
                },
                {
                    "name": "RHSA-2019:1700",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:1700"
                },
                {
                    "name": "[debian-lts-announce] 20190711 [SECURITY] [DLA 1852-1] python3.4 security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html"
                },
                {
                    "name": "FEDORA-2019-9bfb4a3e4b",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_FEDORA"
                    ],
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/"
                },
                {
                    "name": "FEDORA-2019-60a1defcd1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_FEDORA"
                    ],
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/"
                },
                {
                    "name": "RHSA-2019:2030",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:2030"
                },
                {
                    "name": "USN-4127-2",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "https://usn.ubuntu.com/4127-2/"
                },
                {
                    "name": "USN-4127-1",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_UBUNTU"
                    ],
                    "url": "https://usn.ubuntu.com/4127-1/"
                },
                {
                    "name": "20191021 [slackware-security] python (SSA:2019-293-01)",
                    "tags": [
                        "mailing-list",
                        "x_refsource_BUGTRAQ"
                    ],
                    "url": "https://seclists.org/bugtraq/2019/Oct/29"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html"
                },
                {
                    "name": "RHSA-2019:3335",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                },
                {
                    "name": "RHSA-2019:3520",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:3520"
                },
                {
                    "name": "GLSA-202003-26",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_GENTOO"
                    ],
                    "url": "https://security.gentoo.org/glsa/202003-26"
                },
                {
                    "name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
                },
                {
                    "name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E"
                },
                {
                    "name": "[debian-lts-announce] 20200822 [SECURITY] [DLA 2337-1] python2.7 security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_MLIST"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2019-9948",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugs.python.org/issue35907",
                            "refsource": "MISC",
                            "url": "https://bugs.python.org/issue35907"
                        },
                        {
                            "name": "https://github.com/python/cpython/pull/11842",
                            "refsource": "MISC",
                            "url": "https://github.com/python/cpython/pull/11842"
                        },
                        {
                            "name": "107549",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/107549"
                        },
                        {
                            "name": "https://security.netapp.com/advisory/ntap-20190404-0004/",
                            "refsource": "CONFIRM",
                            "url": "https://security.netapp.com/advisory/ntap-20190404-0004/"
                        },
                        {
                            "name": "openSUSE-SU-2019:1273",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html"
                        },
                        {
                            "name": "openSUSE-SU-2019:1580",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html"
                        },
                        {
                            "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
                        },
                        {
                            "name": "RHSA-2019:1700",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:1700"
                        },
                        {
                            "name": "[debian-lts-announce] 20190711 [SECURITY] [DLA 1852-1] python3.4 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html"
                        },
                        {
                            "name": "FEDORA-2019-9bfb4a3e4b",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES/"
                        },
                        {
                            "name": "FEDORA-2019-60a1defcd1",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L/"
                        },
                        {
                            "name": "RHSA-2019:2030",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:2030"
                        },
                        {
                            "name": "USN-4127-2",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4127-2/"
                        },
                        {
                            "name": "USN-4127-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/4127-1/"
                        },
                        {
                            "name": "20191021 [slackware-security] python (SSA:2019-293-01)",
                            "refsource": "BUGTRAQ",
                            "url": "https://seclists.org/bugtraq/2019/Oct/29"
                        },
                        {
                            "name": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html",
                            "refsource": "MISC",
                            "url": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html"
                        },
                        {
                            "name": "RHSA-2019:3335",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                        },
                        {
                            "name": "RHSA-2019:3520",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:3520"
                        },
                        {
                            "name": "GLSA-202003-26",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/202003-26"
                        },
                        {
                            "name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html"
                        },
                        {
                            "name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
                            "refsource": "MLIST",
                            "url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0@%3Cissues.bookkeeper.apache.org%3E"
                        },
                        {
                            "name": "[debian-lts-announce] 20200822 [SECURITY] [DLA 2337-1] python2.7 security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-07-02T19:14:39.838Z"
                },
                "references": [
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://bugs.python.org/issue35907/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://github.com/python/cpython/pull/11842/DEMO_2024_06_19"
                    },
                    {
                        "name": "107549",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.securityfocus.com/bid/107549/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://security.netapp.com/advisory/ntap-20190404-0004//DEMO_2024_06_19"
                    },
                    {
                        "name": "openSUSE-SU-2019:1273",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "openSUSE-SU-2019:1580",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2019:1700",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:1700/DEMO_2024_06_19"
                    },
                    {
                        "name": "[debian-lts-announce] 20190711 [SECURITY] [DLA 1852-1] python3.4 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "FEDORA-2019-9bfb4a3e4b",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_FEDORA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES//DEMO_2024_06_19"
                    },
                    {
                        "name": "FEDORA-2019-60a1defcd1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_FEDORA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L//DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2019:2030",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:2030/DEMO_2024_06_19"
                    },
                    {
                        "name": "USN-4127-2",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://usn.ubuntu.com/4127-2//DEMO_2024_06_19"
                    },
                    {
                        "name": "USN-4127-1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://usn.ubuntu.com/4127-1//DEMO_2024_06_19"
                    },
                    {
                        "name": "20191021 [slackware-security] python (SSA:2019-293-01)",
                        "tags": [
                            "mailing-list",
                            "x_refsource_BUGTRAQ",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://seclists.org/bugtraq/2019/Oct/29/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2019:3335",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:3335/DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2019:3520",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:3520/DEMO_2024_06_19"
                    },
                    {
                        "name": "GLSA-202003-26",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_GENTOO",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://security.gentoo.org/glsa/202003-26/DEMO_2024_06_19"
                    },
                    {
                        "name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E/DEMO_2024_06_19"
                    },
                    {
                        "name": "[debian-lts-announce] 20200822 [SECURITY] [DLA 2337-1] python2.7 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://bugs.python.org/issue35907/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://github.com/python/cpython/pull/11842/adp-test-6-28"
                    },
                    {
                        "name": "107549",
                        "tags": [
                            "vdb-entry",
                            "x_refsource_BID",
                            "x_snapshot"
                        ],
                        "url": "http://www.securityfocus.com/bid/107549/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_snapshot"
                        ],
                        "url": "https://security.netapp.com/advisory/ntap-20190404-0004//adp-test-6-28"
                    },
                    {
                        "name": "openSUSE-SU-2019:1273",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html/adp-test-6-28"
                    },
                    {
                        "name": "openSUSE-SU-2019:1580",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00050.html/adp-test-6-28"
                    },
                    {
                        "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html/adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2019:1700",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:1700/adp-test-6-28"
                    },
                    {
                        "name": "[debian-lts-announce] 20190711 [SECURITY] [DLA 1852-1] python3.4 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2019/07/msg00011.html/adp-test-6-28"
                    },
                    {
                        "name": "FEDORA-2019-9bfb4a3e4b",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_FEDORA",
                            "x_snapshot"
                        ],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KRYFIMISZ47NTAU3XWZUOFB7CYL62KES//adp-test-6-28"
                    },
                    {
                        "name": "FEDORA-2019-60a1defcd1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_FEDORA",
                            "x_snapshot"
                        ],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HQEQLXLOCR3SNM3AA5RRYJFQ5AZBYJ4L//adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2019:2030",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:2030/adp-test-6-28"
                    },
                    {
                        "name": "USN-4127-2",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_snapshot"
                        ],
                        "url": "https://usn.ubuntu.com/4127-2//adp-test-6-28"
                    },
                    {
                        "name": "USN-4127-1",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_UBUNTU",
                            "x_snapshot"
                        ],
                        "url": "https://usn.ubuntu.com/4127-1//adp-test-6-28"
                    },
                    {
                        "name": "20191021 [slackware-security] python (SSA:2019-293-01)",
                        "tags": [
                            "mailing-list",
                            "x_refsource_BUGTRAQ",
                            "x_snapshot"
                        ],
                        "url": "https://seclists.org/bugtraq/2019/Oct/29/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "http://packetstormsecurity.com/files/154927/Slackware-Security-Advisory-python-Updates.html/adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2019:3335",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:3335/adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2019:3520",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_snapshot"
                        ],
                        "url": "https://access.redhat.com/errata/RHSA-2019:3520/adp-test-6-28"
                    },
                    {
                        "name": "GLSA-202003-26",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_GENTOO",
                            "x_snapshot"
                        ],
                        "url": "https://security.gentoo.org/glsa/202003-26/adp-test-6-28"
                    },
                    {
                        "name": "[debian-lts-announce] 20200715 [SECURITY] [DLA 2280-1] python3.5 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html/adp-test-6-28"
                    },
                    {
                        "name": "[bookkeeper-issues] 20200729 [GitHub] [bookkeeper] padma81 opened a new issue #2387: Security vulnerabilities in the apache/bookkeeper-4.9.2 image",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_snapshot"
                        ],
                        "url": "https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E/adp-test-6-28"
                    },
                    {
                        "name": "[debian-lts-announce] 20200822 [SECURITY] [DLA 2337-1] python2.7 security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_MLIST",
                            "x_snapshot"
                        ],
                        "url": "https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2019-9948",
        "datePublished": "2019-03-23T17:07:08",
        "dateReserved": "2019-03-23T00:00:00",
        "dateUpdated": "2024-07-02T19:14:39.838Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}