{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2006-03-18T00:00:00",
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Stack-based buffer overflow in Python 2.4.2 and earlier, running on Linux 2.6.12.5 under gcc 4.0.3 with libc 2.3.5, allows local users to cause a \"stack overflow,\" and possibly gain privileges, by running a script from a current working directory that has a long name, related to the realpath function.  NOTE: this might not be a vulnerability. However, the fact that it appears in a programming language interpreter could mean that some applications are affected, although attack scenarios might be limited because the attacker might already need to cross privilege boundaries to cause an exploitable program to be placed in a directory with a long name; or, depending on the method that Python uses to determine the current working directory, setuid applications might be affected."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2017-10-18T16:57:01",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "31492",
                    "tags": [
                        "third-party-advisory",
                        "x_refsource_SECUNIA"
                    ],
                    "url": "http://secunia.com/advisories/31492"
                },
                {
                    "name": "RHSA-2008:0629",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_REDHAT"
                    ],
                    "url": "http://www.redhat.com/support/errata/RHSA-2008-0629.html"
                },
                {
                    "name": "1591",
                    "tags": [
                        "exploit",
                        "x_refsource_EXPLOIT-DB"
                    ],
                    "url": "https://www.exploit-db.com/exploits/1591"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "http://www.gotfault.net/research/exploit/gexp-python.py"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2006-1542",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Stack-based buffer overflow in Python 2.4.2 and earlier, running on Linux 2.6.12.5 under gcc 4.0.3 with libc 2.3.5, allows local users to cause a \"stack overflow,\" and possibly gain privileges, by running a script from a current working directory that has a long name, related to the realpath function.  NOTE: this might not be a vulnerability. However, the fact that it appears in a programming language interpreter could mean that some applications are affected, although attack scenarios might be limited because the attacker might already need to cross privilege boundaries to cause an exploitable program to be placed in a directory with a long name; or, depending on the method that Python uses to determine the current working directory, setuid applications might be affected."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "31492",
                            "refsource": "SECUNIA",
                            "url": "http://secunia.com/advisories/31492"
                        },
                        {
                            "name": "RHSA-2008:0629",
                            "refsource": "REDHAT",
                            "url": "http://www.redhat.com/support/errata/RHSA-2008-0629.html"
                        },
                        {
                            "name": "1591",
                            "refsource": "EXPLOIT-DB",
                            "url": "https://www.exploit-db.com/exploits/1591"
                        },
                        {
                            "name": "http://www.gotfault.net/research/exploit/gexp-python.py",
                            "refsource": "MISC",
                            "url": "http://www.gotfault.net/research/exploit/gexp-python.py"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-06-29T03:43:06.533Z"
                },
                "references": [
                    {
                        "name": "31492",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://secunia.com/advisories/31492/DEMO_2024_06_19"
                    },
                    {
                        "name": "RHSA-2008:0629",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.redhat.com/support/errata/RHSA-2008-0629.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "1591",
                        "tags": [
                            "exploit",
                            "x_refsource_EXPLOIT-DB",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://www.exploit-db.com/exploits/1591/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://www.gotfault.net/research/exploit/gexp-python.py/DEMO_2024_06_19"
                    },
                    {
                        "name": "31492",
                        "tags": [
                            "third-party-advisory",
                            "x_refsource_SECUNIA",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://secunia.com/advisories/31492/adp-test-6-28"
                    },
                    {
                        "name": "RHSA-2008:0629",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_REDHAT",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.redhat.com/support/errata/RHSA-2008-0629.html/adp-test-6-28"
                    },
                    {
                        "name": "1591",
                        "tags": [
                            "exploit",
                            "x_refsource_EXPLOIT-DB",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "https://www.exploit-db.com/exploits/1591/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot",
                            "x_cve_prog_secretariat_snapshot@2024-06-28T20:08:51.933Z"
                        ],
                        "url": "http://www.gotfault.net/research/exploit/gexp-python.py/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2006-1542",
        "datePublished": "2006-03-30T11:00:00",
        "dateReserved": "2006-03-30T00:00:00",
        "dateUpdated": "2024-06-29T03:43:06.533Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}