{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2020-05-01T01:06:11",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://docs.djangoproject.com/en/dev/releases/security/"
                },
                {
                    "tags": [
                        "x_refsource_MISC"
                    ],
                    "url": "https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
                },
                {
                    "name": "20190812 [SECURITY] [DSA 4498-1] python-django security update",
                    "tags": [
                        "mailing-list",
                        "x_refsource_BUGTRAQ"
                    ],
                    "url": "https://seclists.org/bugtraq/2019/Aug/15"
                },
                {
                    "name": "DSA-4498",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_DEBIAN"
                    ],
                    "url": "https://www.debian.org/security/2019/dsa-4498"
                },
                {
                    "name": "openSUSE-SU-2019:1872",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_SUSE"
                    ],
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html"
                },
                {
                    "name": "FEDORA-2019-647f74ce51",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_FEDORA"
                    ],
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK/"
                },
                {
                    "tags": [
                        "x_refsource_CONFIRM"
                    ],
                    "url": "https://security.netapp.com/advisory/ntap-20190828-0002/"
                },
                {
                    "name": "GLSA-202004-17",
                    "tags": [
                        "vendor-advisory",
                        "x_refsource_GENTOO"
                    ],
                    "url": "https://security.gentoo.org/glsa/202004-17"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2019-14234",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://docs.djangoproject.com/en/dev/releases/security/",
                            "refsource": "MISC",
                            "url": "https://docs.djangoproject.com/en/dev/releases/security/"
                        },
                        {
                            "name": "https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs",
                            "refsource": "MISC",
                            "url": "https://groups.google.com/forum/#!topic/django-announce/jIoju2-KLDs"
                        },
                        {
                            "name": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
                            "refsource": "CONFIRM",
                            "url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
                        },
                        {
                            "name": "20190812 [SECURITY] [DSA 4498-1] python-django security update",
                            "refsource": "BUGTRAQ",
                            "url": "https://seclists.org/bugtraq/2019/Aug/15"
                        },
                        {
                            "name": "DSA-4498",
                            "refsource": "DEBIAN",
                            "url": "https://www.debian.org/security/2019/dsa-4498"
                        },
                        {
                            "name": "openSUSE-SU-2019:1872",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html"
                        },
                        {
                            "name": "FEDORA-2019-647f74ce51",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK/"
                        },
                        {
                            "name": "https://security.netapp.com/advisory/ntap-20190828-0002/",
                            "refsource": "CONFIRM",
                            "url": "https://security.netapp.com/advisory/ntap-20190828-0002/"
                        },
                        {
                            "name": "GLSA-202004-17",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/202004-17"
                        }
                    ]
                }
            }
        },
        "adp": [
            {
                "providerMetadata": {
                    "orgId": "96f1cf3c-f80a-4e0f-a063-99a91e3f1325",
                    "shortName": "secretariat-reference",
                    "dateUpdated": "2024-07-02T11:02:43.663Z"
                },
                "references": [
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://docs.djangoproject.com/en/dev/releases/security//DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases//DEMO_2024_06_19"
                    },
                    {
                        "name": "20190812 [SECURITY] [DSA 4498-1] python-django security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_BUGTRAQ",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://seclists.org/bugtraq/2019/Aug/15/DEMO_2024_06_19"
                    },
                    {
                        "name": "DSA-4498",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_DEBIAN",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://www.debian.org/security/2019/dsa-4498/DEMO_2024_06_19"
                    },
                    {
                        "name": "openSUSE-SU-2019:1872",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html/DEMO_2024_06_19"
                    },
                    {
                        "name": "FEDORA-2019-647f74ce51",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_FEDORA",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK//DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://security.netapp.com/advisory/ntap-20190828-0002//DEMO_2024_06_19"
                    },
                    {
                        "name": "GLSA-202004-17",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_GENTOO",
                            "x_cve_prog_secretariat_snapshot"
                        ],
                        "url": "https://security.gentoo.org/glsa/202004-17/DEMO_2024_06_19"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://docs.djangoproject.com/en/dev/releases/security//adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_MISC",
                            "x_snapshot"
                        ],
                        "url": "https://groups.google.com/forum/#%21topic/django-announce/jIoju2-KLDs/adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_snapshot"
                        ],
                        "url": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases//adp-test-6-28"
                    },
                    {
                        "name": "20190812 [SECURITY] [DSA 4498-1] python-django security update",
                        "tags": [
                            "mailing-list",
                            "x_refsource_BUGTRAQ",
                            "x_snapshot"
                        ],
                        "url": "https://seclists.org/bugtraq/2019/Aug/15/adp-test-6-28"
                    },
                    {
                        "name": "DSA-4498",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_DEBIAN",
                            "x_snapshot"
                        ],
                        "url": "https://www.debian.org/security/2019/dsa-4498/adp-test-6-28"
                    },
                    {
                        "name": "openSUSE-SU-2019:1872",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_SUSE",
                            "x_snapshot"
                        ],
                        "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html/adp-test-6-28"
                    },
                    {
                        "name": "FEDORA-2019-647f74ce51",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_FEDORA",
                            "x_snapshot"
                        ],
                        "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/STVX7X7IDWAH5SKE6MBMY3TEI6ZODBTK//adp-test-6-28"
                    },
                    {
                        "tags": [
                            "x_refsource_CONFIRM",
                            "x_snapshot"
                        ],
                        "url": "https://security.netapp.com/advisory/ntap-20190828-0002//adp-test-6-28"
                    },
                    {
                        "name": "GLSA-202004-17",
                        "tags": [
                            "vendor-advisory",
                            "x_refsource_GENTOO",
                            "x_snapshot"
                        ],
                        "url": "https://security.gentoo.org/glsa/202004-17/adp-test-6-28"
                    }
                ]
            }
        ]
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2019-14234",
        "datePublished": "2019-08-09T12:16:44",
        "dateReserved": "2019-07-22T00:00:00",
        "dateUpdated": "2024-07-02T11:02:43.663Z",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.1"
}